### ISSUE TITLE
Wiring Information / Diagram

### ISSUE THREAD

**Issue by maxwlang** [bigevtaylor/arduino-swc#3]
Hey! First off, love the project!

This is the first time I'm working with car audio in this way, and I've never used a library like AceButton before, so I was hoping you might be able to shed a little light on this for me.

I'm getting this to build fine, but not seeing any results on my radio. I suspect it is likely I may need to identify differing resistance and / or digipot values in order for this to work with my configuration, but I wanted to confirm I didn't have it wired incorrectly, first..

I was wondering, on a couple things:

- What are you using for Arduino hardware? I'm running this on an Arduino Nano.
- My understanding is A6 is connected to the SWC, but I don't know where to connect the output to the radio. Is the tip connected to digital pin 10? If so, do I just ground the ring?

Would love a super simple diagram / photo / explanation if you had the time! Thank you!

**Comment by bigevtaylor** [comment]
Hi,

This is on a Arduino Nano also so will not be an issue for you.

What vehicle is this going into?

The connection to the pin 10 goes to the digipot which is then wired to a 3.5mm stereo jack - 
![](https://i.imgur.com/ZFfHEWL.jpeg)

**Comment by maxwlang** [comment]
This is exactly what I needed, thank you very much! I'm going to try and shim this into a 2012 Ford Fusion SE

**Comment by bigevtaylor** [comment]
Not a problem at all :)

This was the parts list,
1x Arduino Nano
1x MCP4251, 8-Bit Dual Digital POT
1x 10kOhm resistor
1x DC-DC Step-down Convertor

Someone else identified that a dual digipot is not required https://github.com/bigevtaylor/arduino-swc/issues/2

I am not familiar with the Ford Fusion, keen to hear how you go!

**Comment by bigevtaylor** [comment]
Also, run this first to get the read on the resistance ladder, then update the code to suit your vehicle.
https://github.com/bxparks/AceButton/tree/develop/examples/LadderButtonCalibrator

**Comment by maxwlang** [comment]
Yo! Wanted to follow up with my [fork](https://github.com/maxwlang/arduino-swc-ford-fusion), and thank you again for this codebase!

Not terribly different from your implementation, though the way I read from the SWC needed to be tweaked a little bit to read accurate values from the wheel's buttons. I added the `calculateLevel` method for this. Maybe there's a better way to do this, maybe I don't need to do this, I'm not real sure.. but it makes it a lot more precise. C++ is not a language I use very often.

~~Expecting to test it all out today. So far I know signals to the radio from the arduino works, and reading the buttons from the wheel works. Just need to test it together now!~~

Everything works!!

**Comment by bigevtaylor** [comment]
Great news! Excellent work mate :)
