### ISSUE TITLE
Using a Generic Aliexpress Device with an Arduino-SWC to Connect to a Pioneer Radio

### ISSUE THREAD

**Issue by mbuzzo1** [bigevtaylor/arduino-swc#4]
Hello,

Would it be possible to use a generic device from Aliexpress like this one https://www.aliexpress.us/item/3256804517901801.html and connect it via arduino-swc to a Pioneer radio?

I've considered this question because I'm not sure if it's even possible to do such a thing with an ASWC-1, as these are oriented towards the use of an OEM SWC.

Since my vehicle doesn't have its own SWC, I would like to know if by adding a device like the one mentioned earlier and using this project, I could achieve what you have achieved.

**Comment by bigevtaylor** [comment]
No reason why not, it looks to just be using voltage for the buttons. Would need to bench test it to get the output from the receiver. The ASWC-1 is an interface for OEM controls, what you have linked to is a remote unit with a receiver that then connects into the factory wiring or head unit wiring.

My code is not tied to OEM controls, it is just all I had worked with. Give it a go!
